### PR TITLE
Fix for null selectors and respecting specificity.

### PR DESCRIPTION
**Pull request by ekskimn**

### CODE REVIEW

**Comment by mgreter** [comment]
Do you have a test case for this?

**Comment by ekskimn** [comment]
yes, I can provide one

**Comment by mgreter** [comment]
Would be great. But please also post it here as I'm currently rebasing the whole PR and would like to test what your commits actually fix.

**Comment by ekskimn** [comment]
.simple {
  a: selector-replace('foo.bar', 'foo', 'foo[baz]');
}

**Comment by ekskimn** [comment]
expected output:

.simple {
  a: foo.bar[baz]; }

**Comment by ekskimn** [comment]
Also for the child-selector issue:

foo {
	a:&;
	>bar {
		b:&;
		>baz {
			c:&;
		}
	}
}

expected output:

foo {
  a: foo; }
  foo > bar {
    b: foo > bar; }
    foo > bar > baz {
      c: foo > bar > baz; }

**Comment by ekskimn** [comment]
ugh...sorry about the formatting....

**Comment by mgreter** [comment]
I have cherry picked your commits and removed a few more bits!
So please check if this branch still fixes all your issues: https://github.com/sass/libsass/pull/1249!
Also please open Bug Report for libsass or a PR for sass-spec with these tests!

Thank you!

**Comment by ekskimn** [comment]
yup~! those are my commits~!

issues 
libsass#1304 
libsass#1303
created

https://github.com/sass/libsass/issues/1304

**Pull request closed without merging**
